name: on push
on: push

jobs:
  build:
    name: "build go binary"
    runs-on: ubuntu-latest
    steps:
    - name: clone repo with latest
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build binary
      run: |
        echo I am building go binary